# Generated by Django 4.0.3 on 2022-03-14 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.team')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('SingleElim', 'Single-elimination')], max_length=20)),
                ('target_size', models.IntegerField(choices=[(2, '2'), (4, '4'), (8, '8'), (16, '16')])),
                ('start_date', models.DateTimeField()),
                ('participants', models.ManyToManyField(through='tournament.Participation', to='accounts.team')),
            ],
        ),
        migrations.AddField(
            model_name='participation',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.GenericIPAddressField()),
                ('server_port', models.IntegerField()),
                ('result', models.CharField(max_length=10)),
                ('start_date', models.DateTimeField()),
                ('left_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_left_team', to='accounts.team')),
                ('right_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_right_team', to='accounts.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
    ]
